# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='usercmd',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbase.proto\x12\x07usercmd\"\x1b\n\x0bLoginC2SMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0bLoginS2CMsg\x12\x10\n\x08PlayerId\x18\x01 \x01(\r\"\x10\n\x0eIntoRoomC2SMsg\" \n\x0eIntoRoomS2CMsg\x12\x0e\n\x06RoomId\x18\x01 \x01(\r\"\xb1\x01\n\x0c\x42\x61ttleEntity\x12\x10\n\x08PosIndex\x18\x01 \x01(\r\x12\x12\n\nEntityType\x18\x02 \x01(\r\x12\x0e\n\x06Health\x18\x03 \x01(\r\x12\x16\n\x0ePhysicalAttack\x18\x04 \x01(\r\x12\x13\n\x0bMagicAttack\x18\x05 \x01(\r\x12\x16\n\x0ePhysicalDefend\x18\x06 \x01(\r\x12\x13\n\x0bMagicDefend\x18\x07 \x01(\r\x12\x11\n\tMoveSpeed\x18\x08 \x01(\r\"F\n\x1bSyncAllBattleEntitiesS2CMsg\x12\'\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x15.usercmd.BattleEntity\"k\n\x0eTurnInfoS2CMsg\x12\x14\n\x0c\x42igTurnIndex\x18\x01 \x01(\r\x12\x16\n\x0eSmallTurnIndex\x18\x02 \x01(\r\x12\x19\n\x11\x43urEntityPosIndex\x18\x03 \x01(\r\x12\x10\n\x08SkillSet\x18\x04 \x03(\r\"5\n\x0f\x43\x61stSkillC2SMsg\x12\x0f\n\x07SkillId\x18\x01 \x01(\r\x12\x11\n\tTargetIds\x18\x02 \x03(\r\"j\n\x11SkillResultS2CMsg\x12\x0f\n\x07SkillId\x18\x01 \x01(\r\x12\x10\n\x08\x43\x61sterId\x18\x02 \x01(\r\x12\x10\n\x08TargetId\x18\x03 \x01(\r\x12\x13\n\x0bOperationId\x18\x04 \x01(\r\x12\x0b\n\x03\x41rg\x18\x05 \x01(\r*\xa4\x01\n\x07\x43mdType\x12\x0c\n\x08LoginReq\x10\x00\x12\x0c\n\x08LoginRes\x10\x01\x12\x0f\n\x0bIntoRoomReq\x10\x02\x12\x0f\n\x0bIntoRoomRes\x10\x03\x12\x19\n\x15SyncAllBattleEntities\x10\x04\x12\x0c\n\x08TurnInfo\x10\x05\x12\x10\n\x0c\x43\x61stSkillReq\x10\x06\x12\x12\n\x0eSkillResultRes\x10\x07\x12\x0c\n\x08MaxCmdId\x10\x08*d\n\x08PosIndex\x12\x0c\n\x08PosELeft\x10\x00\x12\x0e\n\nPosECenter\x10\x01\x12\r\n\tPosERight\x10\x02\x12\x0c\n\x08PosBLeft\x10\x03\x12\x0e\n\nPosBCenter\x10\x04\x12\r\n\tPosBRight\x10\x05*+\n\tOperation\x12\x08\n\x04None\x10\x00\x12\n\n\x06\x44\x61mage\x10\x01\x12\x08\n\x04Heal\x10\x02\x62\x06proto3')
)

_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='usercmd.CmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LoginReq', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LoginRes', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntoRoomReq', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntoRoomRes', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SyncAllBattleEntities', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TurnInfo', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CastSkillReq', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SkillResultRes', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MaxCmdId', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=662,
  serialized_end=826,
)
_sym_db.RegisterEnumDescriptor(_CMDTYPE)

CmdType = enum_type_wrapper.EnumTypeWrapper(_CMDTYPE)
_POSINDEX = _descriptor.EnumDescriptor(
  name='PosIndex',
  full_name='usercmd.PosIndex',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PosELeft', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PosECenter', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PosERight', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PosBLeft', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PosBCenter', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PosBRight', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=828,
  serialized_end=928,
)
_sym_db.RegisterEnumDescriptor(_POSINDEX)

PosIndex = enum_type_wrapper.EnumTypeWrapper(_POSINDEX)
_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='usercmd.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Damage', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Heal', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=930,
  serialized_end=973,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
LoginReq = 0
LoginRes = 1
IntoRoomReq = 2
IntoRoomRes = 3
SyncAllBattleEntities = 4
TurnInfo = 5
CastSkillReq = 6
SkillResultRes = 7
MaxCmdId = 8
PosELeft = 0
PosECenter = 1
PosERight = 2
PosBLeft = 3
PosBCenter = 4
PosBRight = 5
globals()['None'] = 0
Damage = 1
Heal = 2



_LOGINC2SMSG = _descriptor.Descriptor(
  name='LoginC2SMsg',
  full_name='usercmd.LoginC2SMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='usercmd.LoginC2SMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)


_LOGINS2CMSG = _descriptor.Descriptor(
  name='LoginS2CMsg',
  full_name='usercmd.LoginS2CMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PlayerId', full_name='usercmd.LoginS2CMsg.PlayerId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=83,
)


_INTOROOMC2SMSG = _descriptor.Descriptor(
  name='IntoRoomC2SMsg',
  full_name='usercmd.IntoRoomC2SMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=101,
)


_INTOROOMS2CMSG = _descriptor.Descriptor(
  name='IntoRoomS2CMsg',
  full_name='usercmd.IntoRoomS2CMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoomId', full_name='usercmd.IntoRoomS2CMsg.RoomId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=135,
)


_BATTLEENTITY = _descriptor.Descriptor(
  name='BattleEntity',
  full_name='usercmd.BattleEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PosIndex', full_name='usercmd.BattleEntity.PosIndex', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EntityType', full_name='usercmd.BattleEntity.EntityType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Health', full_name='usercmd.BattleEntity.Health', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PhysicalAttack', full_name='usercmd.BattleEntity.PhysicalAttack', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MagicAttack', full_name='usercmd.BattleEntity.MagicAttack', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PhysicalDefend', full_name='usercmd.BattleEntity.PhysicalDefend', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MagicDefend', full_name='usercmd.BattleEntity.MagicDefend', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MoveSpeed', full_name='usercmd.BattleEntity.MoveSpeed', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=315,
)


_SYNCALLBATTLEENTITIESS2CMSG = _descriptor.Descriptor(
  name='SyncAllBattleEntitiesS2CMsg',
  full_name='usercmd.SyncAllBattleEntitiesS2CMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entities', full_name='usercmd.SyncAllBattleEntitiesS2CMsg.entities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=387,
)


_TURNINFOS2CMSG = _descriptor.Descriptor(
  name='TurnInfoS2CMsg',
  full_name='usercmd.TurnInfoS2CMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BigTurnIndex', full_name='usercmd.TurnInfoS2CMsg.BigTurnIndex', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SmallTurnIndex', full_name='usercmd.TurnInfoS2CMsg.SmallTurnIndex', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CurEntityPosIndex', full_name='usercmd.TurnInfoS2CMsg.CurEntityPosIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SkillSet', full_name='usercmd.TurnInfoS2CMsg.SkillSet', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=496,
)


_CASTSKILLC2SMSG = _descriptor.Descriptor(
  name='CastSkillC2SMsg',
  full_name='usercmd.CastSkillC2SMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SkillId', full_name='usercmd.CastSkillC2SMsg.SkillId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TargetIds', full_name='usercmd.CastSkillC2SMsg.TargetIds', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=551,
)


_SKILLRESULTS2CMSG = _descriptor.Descriptor(
  name='SkillResultS2CMsg',
  full_name='usercmd.SkillResultS2CMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SkillId', full_name='usercmd.SkillResultS2CMsg.SkillId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CasterId', full_name='usercmd.SkillResultS2CMsg.CasterId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TargetId', full_name='usercmd.SkillResultS2CMsg.TargetId', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OperationId', full_name='usercmd.SkillResultS2CMsg.OperationId', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Arg', full_name='usercmd.SkillResultS2CMsg.Arg', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=659,
)

_SYNCALLBATTLEENTITIESS2CMSG.fields_by_name['entities'].message_type = _BATTLEENTITY
DESCRIPTOR.message_types_by_name['LoginC2SMsg'] = _LOGINC2SMSG
DESCRIPTOR.message_types_by_name['LoginS2CMsg'] = _LOGINS2CMSG
DESCRIPTOR.message_types_by_name['IntoRoomC2SMsg'] = _INTOROOMC2SMSG
DESCRIPTOR.message_types_by_name['IntoRoomS2CMsg'] = _INTOROOMS2CMSG
DESCRIPTOR.message_types_by_name['BattleEntity'] = _BATTLEENTITY
DESCRIPTOR.message_types_by_name['SyncAllBattleEntitiesS2CMsg'] = _SYNCALLBATTLEENTITIESS2CMSG
DESCRIPTOR.message_types_by_name['TurnInfoS2CMsg'] = _TURNINFOS2CMSG
DESCRIPTOR.message_types_by_name['CastSkillC2SMsg'] = _CASTSKILLC2SMSG
DESCRIPTOR.message_types_by_name['SkillResultS2CMsg'] = _SKILLRESULTS2CMSG
DESCRIPTOR.enum_types_by_name['CmdType'] = _CMDTYPE
DESCRIPTOR.enum_types_by_name['PosIndex'] = _POSINDEX
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginC2SMsg = _reflection.GeneratedProtocolMessageType('LoginC2SMsg', (_message.Message,), {
  'DESCRIPTOR' : _LOGINC2SMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.LoginC2SMsg)
  })
_sym_db.RegisterMessage(LoginC2SMsg)

LoginS2CMsg = _reflection.GeneratedProtocolMessageType('LoginS2CMsg', (_message.Message,), {
  'DESCRIPTOR' : _LOGINS2CMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.LoginS2CMsg)
  })
_sym_db.RegisterMessage(LoginS2CMsg)

IntoRoomC2SMsg = _reflection.GeneratedProtocolMessageType('IntoRoomC2SMsg', (_message.Message,), {
  'DESCRIPTOR' : _INTOROOMC2SMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.IntoRoomC2SMsg)
  })
_sym_db.RegisterMessage(IntoRoomC2SMsg)

IntoRoomS2CMsg = _reflection.GeneratedProtocolMessageType('IntoRoomS2CMsg', (_message.Message,), {
  'DESCRIPTOR' : _INTOROOMS2CMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.IntoRoomS2CMsg)
  })
_sym_db.RegisterMessage(IntoRoomS2CMsg)

BattleEntity = _reflection.GeneratedProtocolMessageType('BattleEntity', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEENTITY,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.BattleEntity)
  })
_sym_db.RegisterMessage(BattleEntity)

SyncAllBattleEntitiesS2CMsg = _reflection.GeneratedProtocolMessageType('SyncAllBattleEntitiesS2CMsg', (_message.Message,), {
  'DESCRIPTOR' : _SYNCALLBATTLEENTITIESS2CMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.SyncAllBattleEntitiesS2CMsg)
  })
_sym_db.RegisterMessage(SyncAllBattleEntitiesS2CMsg)

TurnInfoS2CMsg = _reflection.GeneratedProtocolMessageType('TurnInfoS2CMsg', (_message.Message,), {
  'DESCRIPTOR' : _TURNINFOS2CMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.TurnInfoS2CMsg)
  })
_sym_db.RegisterMessage(TurnInfoS2CMsg)

CastSkillC2SMsg = _reflection.GeneratedProtocolMessageType('CastSkillC2SMsg', (_message.Message,), {
  'DESCRIPTOR' : _CASTSKILLC2SMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.CastSkillC2SMsg)
  })
_sym_db.RegisterMessage(CastSkillC2SMsg)

SkillResultS2CMsg = _reflection.GeneratedProtocolMessageType('SkillResultS2CMsg', (_message.Message,), {
  'DESCRIPTOR' : _SKILLRESULTS2CMSG,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:usercmd.SkillResultS2CMsg)
  })
_sym_db.RegisterMessage(SkillResultS2CMsg)


# @@protoc_insertion_point(module_scope)
